import DocumentList from "@/components/DocumentList";

export default function DocumentsPage() {
  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-xl font-bold tracking-tight text-zinc-100">Document Management</h1>
        <p className="text-xs text-zinc-400 mt-1 leading-relaxed max-w-xl">
          Upload and index raw documents. Preview, manage tags, and inspect individual splits generated by each RAG chunking algorithm.
        </p>
      </div>
      <DocumentList />
    </div>
  );
}
